detectors:
  # You can disable smells completely
  Attribute: # writeable attributes can be used
    enabled: false
  BooleanParameter: # handled by RuboCop
    enabled: false
  ControlParameter: # handled by RuboCop
    enabled: false
  DuplicateMethodCall: # too restrictive
    enabled: false
  FeatureEnvy: # this is a utility gem
    enabled: false
  InstanceVariableAssumption: # recommend to be disabled for rails
    enabled: false
  IrresponsibleModule: # handled by RuboCop
    enabled: false
  LongParameterList: # handled by RuboCop
    enabled: false
  TooManyMethods:
    enabled: true
    max_method_size: 20
  TooManyStatements: # handled by RuboCop
    enabled: false
  UnusedParameters: # handled by RuboCop
    enabled: false
  UtilityFunction: # this is a utility gem
    enabled: false

  # You can use filters to silence Reek warnings.
  # Either because you simply disagree with Reek (we are not the police) or
  # because you want to fix this at a later point in time.
  # NestedIterators:
  #   exclude:
  #     - "MyWorker#self.class_method" # should be refactored
  #     - "AnotherWorker#instance_method" # should be refactored as well

  # A lot of smells allow fine tuning their configuration. You can look up all available options
  # in the corresponding smell documentation in /docs. In most cases you probably can just go
  # with the defaults as documented in defaults.reek.yml.
  # DataClump:
  #   max_copies: 3
  #   min_clump_size: 3

### Directory specific configuration

# You can configure smells on a per-directory base.
# E.g. the classic Rails case: controllers smell of NestedIterators (see /docs/Nested-Iterators.md) and
# helpers smell of UtilityFunction (see docs/Utility-Function.md)
#
# Note that we only allow configuration on a directory level, not a file level,
# so all paths have to point to directories.
# A Dir.glob pattern can be used.
directories:
  "**/test/**":
    FeatureEnvy:
      enabled: false
    TooManyConstants:
      enabled: false
    TooManyMethods:
      max_method_size: 100
    UtilityFunction:
      enabled: false

### Excluding directories

# Directories and files below will not be scanned at all
# exclude_paths:
  # - lib/legacy
  # - lib/rake/legacy_tasks
  # - lib/smelly.rb
