AllCops:
  TargetRubyVersion: 2.6.7
  NewCops: enable
  SuggestExtensions: false

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - test/**/*
    - '*.gemspec'

Metrics/ClassLength:
  Max: 1000

Metrics/MethodLength:
  Max: 50
  Exclude:
    - test/**/*

Metrics/ParameterLists:
  CountKeywordArgs: false
  Max: 7

Naming/FileName:
  Exclude:
    - Rakefile

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - test/**/*

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
